### ISSUE TITLE
security: GitHub Actionsの実行権限を@aku11iに限定

### ISSUE THREAD

**Issue by aku11i** [aku11i/dakenjin#62]
## 概要
claude.ymlワークフローを含むGitHub Actionsの実行権限を、リポジトリオーナー（@aku11i）のみに限定する必要がある。

## 背景・理由
- リポジトリを公開するにあたり、セキュリティリスクを最小化する
- 悪意のあるユーザーによる不正なAction実行を防ぐ
- リソース消費の制御（API呼び出し回数制限など）
- 予期しないワークフロー実行によるコスト発生を防ぐ

## 対象ワークフロー
- `.github/workflows/claude.yml`
- その他の既存・将来追加されるワークフロー

## 実装方法
以下のいずれかまたは組み合わせで実装：

### 1. ワークフロー内での制限
```yaml
jobs:
  job-name:
    if: github.actor == 'aku11i'
    # または
    if: github.repository_owner == 'aku11i'
```

### 2. GitHubリポジトリ設定での制限
- Settings > Actions > General
- "Fork pull request workflows from outside collaborators" の設定
- "Require approval for first-time contributors" の設定

### 3. 環境保護ルールの設定
- 特定の環境での実行時に承認を必要とする設定

## セキュリティ考慮事項
- フォークからのPull Requestでの実行制限
- シークレット情報へのアクセス制限
- 外部コントリビューターからの初回実行時の承認フロー

## 受け入れ条件
- [ ] @aku11i以外のユーザーがワークフローを実行できない
- [ ] フォークリポジトリからのPull Requestでワークフローが自動実行されない
- [ ] 既存の正常なワークフロー実行に影響しない
- [ ] 設定変更がドキュメント化される

## 関連ファイル
- `.github/workflows/claude.yml`
- リポジトリのSettings設定

## 優先度
高 - リポジトリ公開前に対応が必要
